# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

actor = Actor.create(first_name: "Kanye", last_name: "West", known_for: "Singing", age: 35)
actor = Actor.create(first_name: "The Rock", last_name: "Johnson", known_for: "Fast and Furious", age: 40)
actor = Actor.create(first_name: "Eric", last_name: "Roberts", known_for: "King fo the Gypsies", age: 70)
actor = Actor.create(first_name: "Danny", last_name: "Trejo", known_for: "Runaway Train", age: 54)
actor = Actor.create(first_name: "Christopher", last_name: "Lee", known_for: "The Hobbit", age: 68)

movie = Movie.create(title: "The Kings Speech", year: 2010, plot: "At the official closing of the British Empire Exhibition at Wembley Stadium, Prince Albert, Duke of York, the second son of King George V, addresses the crowd with a strong stammer. His search for treatment has been discouraging, but his wife, Elizabeth, persuades him to see the Australian-born Lionel Logue, a non-medically trained Harley Street speech defects therapist. 'Bertie', as he is called by his family, believes the first session is not going well, but Lionel, who insists that all his patients address him as such, has his potential client recite Hamlet's 'To be, or not to be' soliloquy while hearing classical music played on a pair of headphones. Bertie is frustrated at the experiment but Lionel gives him the acetate recording that he has made of the reading as a souvenir. After Bertie's father, King George V, broadcasts his 1934 Royal Christmas Message, he explains to Bertie that the wireless will play a significant part in the role of the royal family, allowing them to enter the homes of the people, and that Bertie's brother's neglect of his responsibilities make training in it necessary. The attempt at reading the message himself is a failure, but that night Bertie plays the recording Lionel gave him and is astonished at the lack of stutter there. He therefore returns for daily treatments to overcome the physical and psychological roots of his speaking difficulty.")

movie = Movie.create(title: "The Revenant", year: 2015, plot: "In late 1823, Hugh Glass guides Captain Andrew Henry's trappers through the territory of the present-day Dakotas. While he and his half-Pawnee son, Hawk, are hunting, the company's camp is attacked by an Arikara war party seeking to recover its Chief's abducted daughter, Powaqa. Many of the trappers are killed during the fight, while the rest of them escape onto a boat. Guided by Glass, the survivors travel on foot to Fort Kiowa, because he believes that traveling downriver will make them vulnerable. After docking, the crew stashes the pelts near the shore.")

movie = Movie.create(title: "The Dune", year: 2021, plot: "In the far future, Duke Leto of House Atreides, ruler of the ocean planet Caladan, is assigned by the Padishah Emperor Shaddam IV of House Corrino to replace House Harkonnen as the fiefholder of Arrakis, a harsh desert planet and the only source of 'spice,' a valuable substance that bestows its users heightened vitality and awareness. It is critical for faster-than-light interstellar travel, as it grants Spacing Guild Navigators the limited prescience needed for safe navigation. Shaddam intends to have House Harkonnen retake the planet with the secret aid of his Sardaukar troops, eradicating House Atreides, which he considers a threat to his power. Leto is reluctant, but sees the advantages of controlling Arrakis and forming an alliance with its native population, skilled fighters known as the Fremen.")
